# Generated by Django 4.1.7 on 2023-03-12 11:02

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='projects',
            fields=[
                ('unique_id', models.AutoField(primary_key=True, serialize=False)),
                ('usertype', models.CharField(default='null', max_length=255)),
                ('title', models.CharField(default='null', max_length=255)),
                ('title_image', models.ImageField(blank=True, null=True, upload_to='projects/')),
                ('description', models.CharField(default='null', max_length=500)),
                ('client', models.CharField(default='null', max_length=255)),
                ('architect', models.CharField(default='null', max_length=255)),
                ('location', models.CharField(default='null', max_length=255)),
                ('size', models.CharField(default='null', max_length=255)),
                ('year_completed', models.CharField(default='null', max_length=255)),
                ('categories', models.CharField(default='null', max_length=255)),
                ('date_added', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
            ],
        ),
        migrations.CreateModel(
            name='projects_image',
            fields=[
                ('unique_id', models.AutoField(primary_key=True, serialize=False)),
                ('image', models.ImageField(blank=True, null=True, upload_to='projects/')),
                ('date_added', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='projects_images', to='projects.projects')),
            ],
        ),
    ]
