# Generated by Django 4.1.7 on 2023-03-13 10:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='projects',
            name='title_image',
        ),
        migrations.AlterField(
            model_name='projects',
            name='architect',
            field=models.CharField(default='null', max_length=100),
        ),
        migrations.AlterField(
            model_name='projects',
            name='client',
            field=models.CharField(default='null', max_length=100),
        ),
        migrations.AlterField(
            model_name='projects',
            name='location',
            field=models.CharField(default='null', max_length=150),
        ),
        migrations.AlterField(
            model_name='projects',
            name='size',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='projects',
            name='year_completed',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='projects_image',
            name='project',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='projects_images_conn', to='projects.projects'),
        ),
    ]
