# Generated by Django 4.1.7 on 2023-03-13 21:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0003_alter_projects_usertype'),
    ]

    operations = [
        migrations.AddField(
            model_name='projects',
            name='user_id',
            field=models.IntegerField(default=0),
        ),
    ]
