# Generated by Django 4.1.7 on 2023-03-16 12:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0005_rename_usertype_projects_user_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projects',
            name='architect',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='projects',
            name='categories',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='projects',
            name='client',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='projects',
            name='description',
            field=models.CharField(max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='projects',
            name='location',
            field=models.CharField(max_length=150, null=True),
        ),
        migrations.AlterField(
            model_name='projects',
            name='title',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='projects',
            name='user_type',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='projects_image',
            name='image',
            field=models.ImageField(blank=True, default='null', upload_to='projects/'),
            preserve_default=False,
        ),
    ]
