# Generated by Django 4.1.7 on 2023-03-17 22:38

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0006_alter_projects_architect_alter_projects_categories_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='messages',
            fields=[
                ('unique_id', models.AutoField(primary_key=True, serialize=False)),
                ('services_id', models.IntegerField(default=0)),
                ('client_user_id', models.IntegerField(default=0)),
                ('builders_user_id', models.IntegerField(default=0)),
                ('architects_user_id', models.IntegerField(default=0)),
                ('civil_engineers_user_id', models.IntegerField(default=0)),
                ('contractors_id', models.IntegerField(default=0)),
                ('messages_text', models.TextField(default='null')),
                ('date_added', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('status', models.CharField(choices=[('contractors', 'Contractors'), ('builders', 'Builders'), ('civil_engineers', 'Civil Engineers'), ('clients', 'Clients'), ('architects', 'Architects')], default='user', max_length=15)),
            ],
        ),
    ]
