# Generated by Django 4.1.7 on 2023-03-21 19:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0008_messages_date_updated_projects_date_updated_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='messages',
            name='status',
        ),
        migrations.AddField(
            model_name='messages',
            name='thread_started_by',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='messages',
            name='thread_started_user_type',
            field=models.CharField(choices=[('contractors', 'Contractors'), ('builders', 'Builders'), ('civil_engineers', 'Civil Engineers'), ('clients', 'Clients'), ('architects', 'Architects')], default='clients', max_length=15),
        ),
        migrations.AddField(
            model_name='messages',
            name='user_type',
            field=models.CharField(choices=[('contractors', 'Contractors'), ('builders', 'Builders'), ('civil_engineers', 'Civil Engineers'), ('clients', 'Clients'), ('architects', 'Architects')], default='clients', max_length=15),
        ),
    ]
