# Generated by Django 4.1.7 on 2023-03-21 19:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('contractors', '0005_registration_business_address_line_1_and_more'),
        ('builders', '0009_business_profile_image_date_updated_and_more'),
        ('clients', '0006_alter_registration_address_line_1_and_more'),
        ('civil_engineers', '0003_registration_date_updated_and_more'),
        ('architects', '0003_alter_registration_address_line_1_and_more'),
        ('projects', '0009_remove_messages_status_messages_thread_started_by_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='messages',
            name='architects_user_id',
        ),
        migrations.RemoveField(
            model_name='messages',
            name='builders_user_id',
        ),
        migrations.RemoveField(
            model_name='messages',
            name='civil_engineers_user_id',
        ),
        migrations.RemoveField(
            model_name='messages',
            name='client_user_id',
        ),
        migrations.RemoveField(
            model_name='messages',
            name='contractors_id',
        ),
        migrations.RemoveField(
            model_name='messages',
            name='thread_started_by',
        ),
        migrations.AddField(
            model_name='messages',
            name='architects_user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='architects.registration'),
        ),
        migrations.AddField(
            model_name='messages',
            name='builders_user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='builders.registration'),
        ),
        migrations.AddField(
            model_name='messages',
            name='civil_engineers_user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='civil_engineers.registration'),
        ),
        migrations.AddField(
            model_name='messages',
            name='client_user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='clients.registration'),
        ),
        migrations.AddField(
            model_name='messages',
            name='contractors_user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='contractors.registration'),
        ),
        migrations.AddField(
            model_name='messages',
            name='thread_started_by_id',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='messages',
            name='messages_text',
            field=models.TextField(default=''),
        ),
        migrations.AlterField(
            model_name='messages',
            name='services_id',
            field=models.IntegerField(null=True),
        ),
    ]
