# Generated by Django 4.1.7 on 2023-03-22 16:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0010_remove_messages_architects_user_id_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='messages_index',
            fields=[
                ('unique_id', models.AutoField(primary_key=True, serialize=False)),
                ('recipient_id', models.IntegerField(null=True)),
                ('recipient_user_type', models.CharField(choices=[('contractors', 'Contractors'), ('builders', 'Builders'), ('civil_engineers', 'Civil Engineers'), ('clients', 'Clients'), ('architects', 'Architects')], default='builders', max_length=20)),
                ('sender_id', models.IntegerField(null=True)),
                ('sender_user_type', models.CharField(choices=[('contractors', 'Contractors'), ('builders', 'Builders'), ('civil_engineers', 'Civil Engineers'), ('clients', 'Clients'), ('architects', 'Architects')], default='clients', max_length=20)),
                ('date_added', models.DateTimeField(auto_now_add=True)),
                ('date_updated', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='messages',
            name='services_id',
        ),
        migrations.RemoveField(
            model_name='messages',
            name='thread_started_by_id',
        ),
        migrations.RemoveField(
            model_name='messages',
            name='thread_started_user_type',
        ),
        migrations.RemoveField(
            model_name='messages',
            name='user_type',
        ),
        migrations.AddField(
            model_name='messages',
            name='msg_index',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='projects.messages_index'),
            preserve_default=False,
        ),
    ]
