# Generated by Django 4.1.7 on 2023-03-23 08:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('builders', '0009_business_profile_image_date_updated_and_more'),
        ('architects', '0003_alter_registration_address_line_1_and_more'),
        ('clients', '0006_alter_registration_address_line_1_and_more'),
        ('contractors', '0005_registration_business_address_line_1_and_more'),
        ('civil_engineers', '0003_registration_date_updated_and_more'),
        ('projects', '0011_messages_index_remove_messages_services_id_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='messages',
            new_name='messages_contain',
        ),
    ]
