# Generated by Django 4.1.7 on 2023-03-23 10:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('builders', '0009_business_profile_image_date_updated_and_more'),
        ('civil_engineers', '0003_registration_date_updated_and_more'),
        ('architects', '0003_alter_registration_address_line_1_and_more'),
        ('contractors', '0005_registration_business_address_line_1_and_more'),
        ('clients', '0006_alter_registration_address_line_1_and_more'),
        ('projects', '0013_alter_messages_contain_msg_index'),
    ]

    operations = [
        migrations.AddField(
            model_name='messages_index',
            name='architects_user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='architects.registration'),
        ),
        migrations.AddField(
            model_name='messages_index',
            name='builders_user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='builders.registration'),
        ),
        migrations.AddField(
            model_name='messages_index',
            name='civil_engineers_user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='civil_engineers.registration'),
        ),
        migrations.AddField(
            model_name='messages_index',
            name='client_user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='clients.registration'),
        ),
        migrations.AddField(
            model_name='messages_index',
            name='contractors_user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='contractors.registration'),
        ),
    ]
