# Generated by Django 4.1.7 on 2023-03-23 10:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0014_messages_index_architects_user_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='messages_index',
            name='recipient_id',
        ),
    ]
