# Generated by Django 4.1.7 on 2023-03-23 10:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0016_rename_architects_user_messages_index_recipient_architects_user_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='messages_index',
            old_name='recipient_architects_user',
            new_name='ind_architects_user',
        ),
        migrations.RenameField(
            model_name='messages_index',
            old_name='recipient_builders_user',
            new_name='ind_builders_user',
        ),
        migrations.RenameField(
            model_name='messages_index',
            old_name='recipient_civil_engineers_user',
            new_name='ind_civil_engineers_user',
        ),
        migrations.RenameField(
            model_name='messages_index',
            old_name='recipient_client_user',
            new_name='ind_client_user',
        ),
        migrations.RenameField(
            model_name='messages_index',
            old_name='recipient_contractors_user',
            new_name='ind_contractors_user',
        ),
        migrations.AddField(
            model_name='messages_index',
            name='sender_user_type',
            field=models.CharField(choices=[('contractors', 'Contractors'), ('builders', 'Builders'), ('civil_engineers', 'Civil Engineers'), ('clients', 'Clients'), ('architects', 'Architects')], default='clients', max_length=20),
        ),
    ]
