# Generated by Django 4.1.7 on 2023-03-23 18:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0017_rename_recipient_architects_user_messages_index_ind_architects_user_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='messages_index',
            name='ind_architects_user',
        ),
        migrations.RemoveField(
            model_name='messages_index',
            name='ind_builders_user',
        ),
        migrations.RemoveField(
            model_name='messages_index',
            name='ind_civil_engineers_user',
        ),
        migrations.RemoveField(
            model_name='messages_index',
            name='ind_client_user',
        ),
        migrations.RemoveField(
            model_name='messages_index',
            name='ind_contractors_user',
        ),
        migrations.AddField(
            model_name='messages_index',
            name='recipient_id',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='messages_index',
            name='sender_id',
            field=models.IntegerField(null=True),
        ),
    ]
