# Generated by Django 4.1.7 on 2023-03-26 21:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0021_business_profile_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='business_profile',
            new_name='user_business_profile',
        ),
    ]
