# Generated by Django 4.1.7 on 2023-03-26 22:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0022_rename_business_profile_user_business_profile'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='business_profile_image',
            name='business_profile',
        ),
        migrations.AddField(
            model_name='business_profile_image',
            name='user',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, related_name='business_profie_image_conn', to='projects.user_registration'),
        ),
        migrations.AddField(
            model_name='user_registration',
            name='business_address_line_1',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='user_registration',
            name='business_address_line_2',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='user_registration',
            name='business_banner_photo',
            field=models.ImageField(blank=True, upload_to='builders/'),
        ),
        migrations.AddField(
            model_name='user_registration',
            name='business_description',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='user_registration',
            name='business_district',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='user_registration',
            name='business_email_address',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='user_registration',
            name='business_mobile_number',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='user_registration',
            name='business_pin_code',
            field=models.CharField(blank=True, max_length=6, null=True),
        ),
        migrations.AddField(
            model_name='user_registration',
            name='business_solution',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='user_registration',
            name='business_state',
            field=models.CharField(blank=True, max_length=40, null=True),
        ),
        migrations.AddField(
            model_name='user_registration',
            name='business_title',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.DeleteModel(
            name='user_business_profile',
        ),
    ]
