# Generated by Django 4.1.7 on 2023-03-26 22:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0023_remove_business_profile_image_business_profile_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='business_profile_image',
            name='user',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, related_name='business_profile_image_conn', to='projects.user_registration'),
        ),
    ]
