# Generated by Django 4.1.7 on 2023-03-28 06:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0024_alter_business_profile_image_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='user_registration',
            name='business_profile_status',
            field=models.CharField(choices=[('pending', 'Pending'), ('active', 'Active')], default='pending', max_length=15),
        ),
    ]
