# Generated by Django 4.1.7 on 2023-03-28 13:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0025_user_registration_business_profile_status'),
    ]

    operations = [
        migrations.RenameField(
            model_name='projects',
            old_name='year_completed',
            new_name='end_date',
        ),
        migrations.RemoveField(
            model_name='projects',
            name='user_type',
        ),
        migrations.AddField(
            model_name='projects',
            name='msg_index',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='projects.messages_index'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='projects',
            name='start_date',
            field=models.IntegerField(default=0),
        ),
    ]
