# Generated by Django 4.1.7 on 2023-03-28 13:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0026_rename_year_completed_projects_end_date_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='projects',
            name='architect',
        ),
        migrations.RemoveField(
            model_name='projects',
            name='user_id',
        ),
        migrations.AddField(
            model_name='projects',
            name='user',
            field=models.ForeignKey(default=2, on_delete=django.db.models.deletion.CASCADE, to='projects.user_registration'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='projects',
            name='client',
            field=models.CharField(max_length=150, null=True),
        ),
    ]
