# Generated by Django 4.1.7 on 2023-03-28 13:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0028_remove_projects_client_remove_projects_user_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projects',
            name='end_date',
            field=models.CharField(default=0, max_length=10),
        ),
        migrations.AlterField(
            model_name='projects',
            name='start_date',
            field=models.CharField(default=0, max_length=10),
        ),
    ]
