# Generated by Django 4.1.7 on 2023-03-29 08:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0030_projects_project_status_projects_publish'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projects',
            name='categories',
            field=models.CharField(choices=[('residential', 'Residential'), ('commercial', 'Commercial'), ('education', 'Education'), ('government', 'Government'), ('infrastructure', 'Infrastructure'), ('healthcare', 'Healthcare')], default='residential', max_length=15),
        ),
    ]
