# Generated by Django 4.1.7 on 2023-03-29 10:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0032_projects_tags'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='projects',
            name='client_id',
        ),
        migrations.RemoveField(
            model_name='projects',
            name='user_id',
        ),
        migrations.AddField(
            model_name='projects',
            name='client',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, related_name='client_projects', to='projects.user_registration'),
        ),
        migrations.AddField(
            model_name='projects',
            name='user',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, related_name='user_projects', to='projects.user_registration'),
        ),
    ]
