# Generated by Django 4.1.7 on 2023-03-30 05:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0033_remove_projects_client_id_remove_projects_user_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='messages_contain',
            name='message_type',
            field=models.CharField(choices=[('normal', 'Normal'), ('project', 'Project')], default='normal', max_length=15),
        ),
    ]
