# Generated by Django 4.1.7 on 2023-03-30 22:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0034_messages_contain_message_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='message_participants',
            fields=[
                ('unique_id', models.AutoField(primary_key=True, serialize=False)),
                ('participant_user_type', models.CharField(choices=[('sender', 'Sender'), ('recipient', 'Recipient'), ('others', 'Others')], default='active', max_length=15)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('active', 'Active')], default='active', max_length=15)),
                ('date_added', models.DateTimeField(auto_now_add=True)),
                ('date_updated', models.DateTimeField(auto_now=True)),
                ('msg_index', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='projects.messages_index')),
                ('participant_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='projects.user_registration')),
            ],
        ),
    ]
