# Generated by Django 4.1.7 on 2023-03-17 08:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('builders', '0006_rename_business_image_business_profile_image'),
    ]

    operations = [
        migrations.RenameField(
            model_name='business_profile_image',
            old_name='user_id',
            new_name='user',
        ),
    ]
