# Generated by Django 4.1.7 on 2023-03-17 10:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('builders', '0007_rename_user_id_business_profile_image_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='registration',
            name='business_solution',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
