# Generated by Django 4.1.7 on 2023-03-20 19:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('builders', '0008_registration_business_solution'),
    ]

    operations = [
        migrations.AddField(
            model_name='business_profile_image',
            name='date_updated',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='registration',
            name='date_updated',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='business_profile_image',
            name='date_added',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='registration',
            name='date_added',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
