# Generated by Django 4.1.7 on 2023-03-07 19:13

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='registration',
            fields=[
                ('unique_id', models.AutoField(primary_key=True, serialize=False)),
                ('firstname', models.CharField(default='null', max_length=100)),
                ('lastname', models.CharField(default='null', max_length=100)),
                ('email', models.CharField(default='null', max_length=255)),
                ('password', models.CharField(default='null', max_length=500)),
                ('phone', models.CharField(default='null', max_length=15)),
                ('profile_photo', models.ImageField(blank=True, null=True, upload_to='FILM_USER/')),
                ('address', models.CharField(default='null', max_length=500)),
                ('district', models.CharField(default='null', max_length=100)),
                ('pin', models.CharField(default='null', max_length=8)),
                ('state', models.CharField(default='null', max_length=10)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('active', 'Active')], default='active', max_length=15)),
                ('date_added', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
            ],
        ),
    ]
