# Generated by Django 4.1.7 on 2023-03-07 22:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='registration',
            old_name='address',
            new_name='address_line_1',
        ),
        migrations.RenameField(
            model_name='registration',
            old_name='email',
            new_name='email_address',
        ),
        migrations.RenameField(
            model_name='registration',
            old_name='firstname',
            new_name='first_name',
        ),
        migrations.RenameField(
            model_name='registration',
            old_name='lastname',
            new_name='last_name',
        ),
        migrations.RenameField(
            model_name='registration',
            old_name='phone',
            new_name='mobile_number',
        ),
        migrations.RenameField(
            model_name='registration',
            old_name='pin',
            new_name='pin_code',
        ),
        migrations.AddField(
            model_name='registration',
            name='address_line_2',
            field=models.CharField(default='null', max_length=500),
        ),
    ]
