# Generated by Django 4.1.7 on 2023-03-11 19:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0002_rename_address_registration_address_line_1_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='registration',
            name='profile_photo',
            field=models.ImageField(blank=True, null=True, upload_to='clients/'),
        ),
    ]
