# Generated by Django 4.1.7 on 2023-03-11 19:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0004_rename_profile_photo_registration_profile_photo1'),
    ]

    operations = [
        migrations.RenameField(
            model_name='registration',
            old_name='profile_photo1',
            new_name='profile_photo',
        ),
    ]
