# Generated by Django 4.1.7 on 2023-03-16 12:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0005_rename_profile_photo1_registration_profile_photo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='registration',
            name='address_line_1',
            field=models.CharField(max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='registration',
            name='address_line_2',
            field=models.CharField(max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='registration',
            name='district',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='registration',
            name='email_address',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='registration',
            name='first_name',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='registration',
            name='last_name',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='registration',
            name='mobile_number',
            field=models.CharField(max_length=15, null=True),
        ),
        migrations.AlterField(
            model_name='registration',
            name='password',
            field=models.CharField(max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='registration',
            name='pin_code',
            field=models.CharField(max_length=8, null=True),
        ),
        migrations.AlterField(
            model_name='registration',
            name='state',
            field=models.CharField(max_length=10, null=True),
        ),
    ]
