# Generated by Django 4.1.7 on 2023-03-26 21:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0021_business_profile_and_more'),
        ('architects', '0003_alter_registration_address_line_1_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='registration',
        ),
    ]
